import Script from "next/script";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
      </head>
      <body>{children}</body>
    </html>
  );
};

export default RootLayout;
